services:
  - type: web
    name: fastapi-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn API.api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: API_URL
        value: https://fastapi-server.onrender.com

  - type: worker
    name: telegram-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bots/telegram_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: API_URL
        value: https://fastapi-server.onrender.com
